apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-project-deployment
spec:
  selector: {}
  template:
    spec:
      containers:
        - name: user-project
          image: 696961721203.dkr.ecr.us-west-2.amazonaws.com/pbl/user-project-service
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: pbl-service-names
            - secretRef:
                name: aws-credentials
