apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: pbl-
bases:
  - github.com/garlic0708/pbl-config-base
commonLabels:
  app: user-project
resources:
  - deployment.yaml
  - service.yaml
